# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20935cf36003e7ec6cb5e6f215163bd03ffa8f1ab6c80d07e45220cbaf298ee17e96114cb895565630cf1ede200a1aebdf9e89d0476e1c4fd0d9f9f109878b71

test:
  secret_key_base: 1ea986b267f24b65422857f319ac58e7b147b9c9f09f8c2341449198ba5cd24d3f88707eafc2371f99acd769c51f75d44c66bfbc90ac2bc75ba34be17db878df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
